services:
    Ray\Di\Injector:
        arguments: ['@App\Ray\Di\AppModule']
        public: true

    # https://symfony.com/doc/current/service_container/synthetic_services.html
    App\Ray\MediaQuery\Query\SaleQueryInterface:
        synthetic: true
